name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "mkms6j790xzvcc9a0giw4s5j"
  title = "functional examples of language"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = "2024-12-09T05:00:00.000Z"
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "tyfrs7p1rvq6929fxjntasww"
  title = "finalize documentation for project"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = "2024-12-11T05:00:00.000Z"
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "ujaio8xsirbv7fcnpfipbdvj"
  title = "working on research elements"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = "2024-12-06T05:00:00.000Z"
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "dwusj2cy3xytnl74jdjekagr"
  title = "Begin planning project procedure"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "muqvqt1mv4ug6bu9wrgdbrwd"
  title = "Initializing project structure stuff "
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = "2024-11-19T05:00:00.000Z"
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
